node->cat: SIMPLE_CMD
node->argv: NULL
node->left: NULL
node->right: NULL
node->cat: PIPE
node->argv: NULL
node->left->cat: CMD
node->right: NULL
node->cat: CMD
node->argv: NULL
node->left->cat: REDIRS
node->right->cat: SIMPLE_CMD
node->cat: REDIRS
node->argv: NULL
node->left->cat: REDIR
node->right->cat: REDIRS
node->cat: REDIR
node->argv[0]: >
node->left: NULL
node->right: NULL
